version: '3.7'


services:
  base: &base
    image: "odykusha/seledka:${DOCKER_ENV}"
    network_mode: host
    working_dir: /work
    volumes:
      - .:/work
      - /dev/shm:/dev/shm
      - /tmp:/tmp
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

  test:
    <<: *base
    entrypoint: pytest -p no:warnings

  browser_stack:
    <<: *base
    entrypoint: browserstack-sdk pytest -p no:warnings
