version: '3.7'


services:
  base: &base
    image: "odykusha/seledka:${HASH_SUM}"
    network_mode: host
    working_dir: /work
    volumes:
      - .:/work

  bash:
    <<: *base
    entrypoint: pytest

  flake8:
    <<: *base
    entrypoint: flake8

  test:
    <<: *base
    entrypoint: pytest -p no:warnings

  browser_version:
    <<: *base
    command: |
      sh -c "
        echo =============== installed browser ================
        google-chrome --version
        chromedriver --version
        echo ==================================================
      "
